
services:
  - type: web
    name: health-tracker-backend
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/healthtracker.jar"
    envVars:
      - key: PORT
        value: 8080
